/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _picture_button_h_
#define _picture_button_h_
//---------------------------------------------------------------------------------
extern const unsigned char picture_button[];
extern const int picture_button_size;
//---------------------------------------------------------------------------------
#endif //_picture_button_h_
//---------------------------------------------------------------------------------
