/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _pictureMenueBackground_h_
#define _pictureMenueBackground_h_
//---------------------------------------------------------------------------------
extern const unsigned char pictureMenueBackground[];
extern const int pictureMenueBackground_size;
//---------------------------------------------------------------------------------
#endif //_pictureMenueBackground_h_
//---------------------------------------------------------------------------------
