/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _picture_loadingbar_h_
#define _picture_loadingbar_h_
//---------------------------------------------------------------------------------
extern const unsigned char picture_loadingbar[];
extern const int picture_loadingbar_size;
//---------------------------------------------------------------------------------
#endif //_picture_loadingbar_h_
//---------------------------------------------------------------------------------
